
server:
    port: 8886
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG
        #查看mybatis语句输出
        com.dhcc.ecm.business.mybatis: DEBUG
        org.springframework.security: DEBUG

spring:
    datasource:       
        url: jdbc:mysql://127.0.0.1:3306/cnnp
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

        #url: jdbc:oracle:thin:@192.168.12.242:1521:orcl
        #username: cnnp
        #password: cnnp
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: oracle.jdbc.OracleDriver
        
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    jackson:
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


